### PR TITLE
Remove unnecessary wrapper from WaitingForOnRampProvider

### PR DESCRIPTION
**Pull request by JustCaptcha**
image

### CODE REVIEW

**Comment by JustynaBroniszewska** [comment]
Could you add screenshots in the wallet and in react (in onboarding flow)? 🙏

**Comment by JustCaptcha** [comment]
image

**Comment by JustynaBroniszewska** [comment]
Ok, thanks for react :) what about wallet?

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image
image
image

**Comment by JustCaptcha** [comment]
image

**Comment by xitronix** [comment]
master version has :
image

**Pull request merged**
