### PR TITLE
Adjustments for the udashboard with device notification

### PR DESCRIPTION
**Pull request by JustCaptcha**

### CODE REVIEW

**Comment by JustCaptcha** [comment]
image

image

**Comment by JustCaptcha** [comment]
image

image

**Comment by JustynaBroniszewska** [comment]
In my opinion under assets should be some margin. It doesn't look good sicked to the bottom of the modal.

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image

**Comment by JustCaptcha** [comment]
image

**Comment by JustynaBroniszewska** [comment]
Responsive version is broken

**Comment by JustCaptcha** [comment]
image

**Pull request merged**
